// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpsloyhmazhmprkpynew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc2xveWhtYXpobXBya3B5bmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjUzNTMsImV4cCI6MjA3Mjc0MTM1M30.tTjib-vYjMZEPU7LGV_wCLORHAuYeQF3ai6bax2cf80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});